### ISSUE TITLE
Great Work

### ISSUE THREAD

**Issue by Thomashighbaugh** [Nooo37/dots#2]
No actual issue here, just saying that your work is top-notch 

Your awesome wm config is actually really, really good and well organized which is a rare enough trait for one that also looks really nice.  I am definitely going to use parts of it locally and adapt it to my own needs, but you are like the one config worth crediting because it does not require completely overhauling your files to adapt them and you actually comment the things in a way that **makes it clear wtf is actually going on**

**Keep up the good work** 

PS I will close this if you don't in a few days!

**Comment by Nooo37** [comment]
Oh wow thank you for those kind words. I surely don't feel like my dots are that well organized most of the time and much of it is stolen. Anyway thank you :smile:
